# Created in Jenkins under Manage > Credentials
KUBE_NAMESPACE=kind-personal-dev
HELM_CHART_DIR=helm_practice/helm-go-web-app
IMAGE_NAME=goserver
DOCKERHUB_USER=larry99
DOCKERHUB_CREDENTIALS=dockerhub-credentials